(function initUiCatalog(root, factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.JeoPARODYUiCatalog = factory();
  }
}(typeof globalThis !== 'undefined' ? globalThis : this, function uiCatalogFactory() {
  'use strict';

  const DialogueStyles = Object.freeze([
    Object.freeze({ id: 'clue-card', label: Object.freeze({ en: 'Clue Card', 'pt-BR': 'Cartão da Pista' }) }),
    Object.freeze({ id: 'speech', label: Object.freeze({ en: 'Comic Speech', 'pt-BR': 'Fala de Quadrinho' }) }),
    Object.freeze({ id: 'thought', label: Object.freeze({ en: 'Host Thought', 'pt-BR': 'Pensamento do Host' }) }),
    Object.freeze({ id: 'narration', label: Object.freeze({ en: 'Narration Box', 'pt-BR': 'Caixa do Narrador' }) }),
  ]);

  const UiCopy = Object.freeze({
    en: Object.freeze({
      lang: 'en',
      questionButton: 'New Clue',
      answerButton: 'Reveal Answer',
      checkButton: 'Lock It In',
      inputPlaceholder: 'Type your response',
      answerFieldLabel: 'Your response',
      checkButtonKicker: 'Confirm',
      questionButtonKicker: 'Board',
      answerButtonKicker: 'Clue',
      askHost: 'Ask Host',
      askHostAboutClue: 'Ask Host about this clue',
      confidencePrompt: 'How did that one feel?',
      confidenceKnew: 'Knew it',
      confidenceShaky: 'Shaky',
      confidenceLearned: 'Learned it',
      disputeJudgment: 'Dispute ruling',
      disputeRecorded: 'Ruling flagged',
      soundOn: 'Sound',
      soundOff: 'Muted',
      voiceMode: 'Voice mode',
      voiceOff: 'Voice off',
      voiceReady: 'Tap to answer',
      voiceNarrationReady: 'Narration on',
      voiceListening: 'Listening...',
      voiceSpeaking: 'Xander speaking',
      voiceDenied: 'Microphone blocked',
      voiceUnavailable: 'Voice unavailable',
      voiceError: 'Voice needs another try',
      voiceHelp: 'Push to talk. Say an answer, next clue, reveal the answer, repeat the clue, open menu, or ask the host.',
      voiceWelcome: 'Voice mode online. Tap the microphone to answer or give me a command.',
      hostPersonality: 'Host personality',
      nextClueReady: 'NEXT CLUE READY',
      themeNight: 'Night',
      themeDay: 'Day',
      languageEnglish: 'English',
      languagePortuguese: 'Português',
      languageSwitchToPortuguese: 'Language: English. Switch to Brazilian Portuguese',
      languageSwitchToEnglish: 'Language: Portuguese. Switch to English',
      translatingClue: 'Translating the complete clue...',
      translationOnDevice: 'PT · ON DEVICE',
      translationNetwork: 'PT · MACHINE',
      translationCache: 'PT · CACHED',
      translationFallback: 'PT unavailable · English shown',
      currentStreak: 'Streak',
      bestStreak: 'Best',
      score: 'Score',
      episode: 'Episode',
      clueProgress: 'Clue',
      episodeComplete: 'Broadcast Complete',
      replayEpisode: 'Replay Episode',
      emptyCategory: 'Host Advisory',
      loadingBank: 'Loading question bank...',
      loadingQuestions: 'Loading questions...',
      fallbackClue: 'There was a problem loading a normal clue. Showing fallback clue.',
      newClue: 'New clue loaded. Enter your answer and press Lock It In.',
      correctKicker: 'Right on the Money',
      correctMessage: 'Correct.',
      correctAnswerStreak: 'Answer streak',
      incorrectKicker: 'The Judges Have Spoken',
      incorrectMessage: 'Not quite.',
      correctResponseLabel: 'Correct response:',
      yourResponseLabel: 'Your response:',
      exactJudgment: 'Exact match',
      variationJudgment: 'Accepted variation',
      fuzzyJudgment: 'Minor typo accepted',
      streakReset: 'STREAK RESET!',
      hostCues: Object.freeze({
        idle: 'On Air',
        clue: 'Your Move',
        reveal: 'The Truth',
        correct: 'Approved',
        incorrect: 'Judges Say No',
        empty: '...Really?',
        streak: 'On Fire',
      }),
      noClue: 'No question available yet. Please load one first.',
      emptyAnswer: 'Please enter an answer before checking.',
      emptyAnswerFallback: 'Try words. They have served contestants reasonably well.',
      keepTyping: 'Type an answer to keep the dignity damage contained.',
      loadedClues: (count) => `Loaded ${count.toLocaleString()} clues.`,
      initializing: 'Initializing game...',
      correctStatus: (scoreDelta, quip) => `Correct. +$${scoreDelta}. ${quip} Press Enter or New Clue to keep rolling.`,
      incorrectStatus: (quip) => `Incorrect. ${quip} Press Enter or New Clue to continue.`,
      voiceClue: (category, value, question) => `${category}, for ${value} dollars. ${question}`,
      voiceCorrect: (value, streak) => `Correct. Add ${value} dollars. Your streak is ${streak}.`,
      voiceIncorrect: (answer) => `Not quite. The correct response was ${answer}.`,
      voiceReveal: (answer) => `The correct response is ${answer}.`,
      voiceComplete: (score, correct, total) => `Broadcast complete. Final score, ${score} dollars. ${correct} correct out of ${total}.`,
    }),
    'pt-BR': Object.freeze({
      lang: 'pt-BR',
      questionButton: 'Nova Pista',
      answerButton: 'Revelar Resposta',
      checkButton: 'Valendo',
      inputPlaceholder: 'Digite sua resposta',
      answerFieldLabel: 'Sua resposta',
      checkButtonKicker: 'Confirmar',
      questionButtonKicker: 'Tabuleiro',
      answerButtonKicker: 'Pista',
      askHost: 'Pergunte ao Host',
      askHostAboutClue: 'Pergunte ao host sobre esta pista',
      confidencePrompt: 'Como foi essa?',
      confidenceKnew: 'Eu sabia',
      confidenceShaky: 'Foi por pouco',
      confidenceLearned: 'Aprendi agora',
      disputeJudgment: 'Contestar decisão',
      disputeRecorded: 'Decisão marcada',
      soundOn: 'Som',
      soundOff: 'Mudo',
      voiceMode: 'Modo de voz',
      voiceOff: 'Voz desligada',
      voiceReady: 'Toque para responder',
      voiceNarrationReady: 'Narração ativa',
      voiceListening: 'Ouvindo...',
      voiceSpeaking: 'Xander falando',
      voiceDenied: 'Microfone bloqueado',
      voiceUnavailable: 'Voz indisponível',
      voiceError: 'Tente a voz novamente',
      voiceHelp: 'Toque para falar. Diga uma resposta, próxima pista, mostre a resposta, repita a pista, abra o menu ou pergunte ao host.',
      voiceWelcome: 'Modo de voz ativado. Toque no microfone para responder ou dar um comando.',
      hostPersonality: 'Personalidade do host',
      nextClueReady: 'PRÓXIMA PISTA',
      themeNight: 'Noite',
      themeDay: 'Dia',
      languageEnglish: 'English',
      languagePortuguese: 'Português',
      languageSwitchToPortuguese: 'Idioma: inglês. Mudar para português do Brasil',
      languageSwitchToEnglish: 'Idioma: português. Mudar para inglês',
      translatingClue: 'Traduzindo categoria, pista e resposta...',
      translationOnDevice: 'PT · NO DISPOSITIVO',
      translationNetwork: 'PT · TRADUÇÃO AUTOMÁTICA',
      translationCache: 'PT · EM CACHE',
      translationFallback: 'PT indisponível · exibindo inglês',
      currentStreak: 'Sequência',
      bestStreak: 'Recorde',
      score: 'Placar',
      episode: 'Episódio',
      clueProgress: 'Pista',
      episodeComplete: 'Transmissão Concluída',
      replayEpisode: 'Repetir Episódio',
      emptyCategory: 'Aviso do Host',
      loadingBank: 'Carregando banco de pistas...',
      loadingQuestions: 'Carregando perguntas...',
      fallbackClue: 'Houve um problema ao carregar uma pista normal. Mostrando uma pista reserva.',
      newClue: 'Nova pista carregada. Digite sua resposta e aperte Valendo.',
      correctKicker: 'Dinheiro no Bolso',
      correctMessage: 'Correto.',
      correctAnswerStreak: 'Sequência de acertos',
      incorrectKicker: 'Os Juízes Decidiram',
      incorrectMessage: 'Quase, mas não.',
      correctResponseLabel: 'Resposta correta:',
      yourResponseLabel: 'Sua resposta:',
      exactJudgment: 'Resposta exata',
      variationJudgment: 'Variação aceita',
      fuzzyJudgment: 'Pequeno erro aceito',
      streakReset: 'SEQUÊNCIA ZERADA!',
      hostCues: Object.freeze({
        idle: 'No Ar',
        clue: 'Sua Vez',
        reveal: 'A Verdade',
        correct: 'Aprovado',
        incorrect: 'Juízes: Não',
        empty: '...Sério?',
        streak: 'Pegando Fogo',
      }),
      noClue: 'Nenhuma pergunta disponível ainda. Carregue uma pista primeiro.',
      emptyAnswer: 'Digite uma resposta antes de conferir.',
      emptyAnswerFallback: 'Tente usar palavras. Elas costumam ajudar.',
      keepTyping: 'Digite uma resposta para conter o dano à dignidade.',
      loadedClues: (count) => `${count.toLocaleString('pt-BR')} pistas carregadas.`,
      initializing: 'Inicializando o jogo...',
      correctStatus: (scoreDelta, quip) => `Correto. +$${scoreDelta}. ${quip} Aperte Enter ou Nova Pista para continuar.`,
      incorrectStatus: (quip) => `Incorreto. ${quip} Aperte Enter ou Nova Pista para continuar.`,
      voiceClue: (category, value, question) => `${category}, por ${value} dólares. ${question}`,
      voiceCorrect: (value, streak) => `Correto. Mais ${value} dólares. Sua sequência é ${streak}.`,
      voiceIncorrect: (answer) => `Quase. A resposta correta era ${answer}.`,
      voiceReveal: (answer) => `A resposta correta é ${answer}.`,
      voiceComplete: (score, correct, total) => `Transmissão concluída. Placar final, ${score} dólares. ${correct} acertos em ${total}.`,
    }),
  });

  function getUiCopy(locale = 'en') {
    return UiCopy[locale] || UiCopy.en;
  }

  return {
    DialogueStyles,
    UiCopy,
    getUiCopy,
  };
}));
