(function initContracts(root, factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.JeopardishContracts = factory();
  }
}(typeof globalThis !== 'undefined' ? globalThis : this, function contractsFactory() {
  'use strict';

  const GameEvents = Object.freeze({
    APPLICATION_COMPOSED: 'APPLICATION_COMPOSED',
    APPLICATION_STARTED: 'APPLICATION_STARTED',
    APPLICATION_STOPPED: 'APPLICATION_STOPPED',
    GAME_INIT: 'GAME_INIT',
    GAME_READY: 'GAME_READY',
    GAME_RESET: 'GAME_RESET',
    GAME_OVER: 'GAME_OVER',
    ROUND_STARTED: 'ROUND_STARTED',
    ROUND_PHASE_CHANGED: 'ROUND_PHASE_CHANGED',
    ROUND_PAUSED: 'ROUND_PAUSED',
    ROUND_RESUMED: 'ROUND_RESUMED',
    STUDY_ENTERED: 'STUDY_ENTERED',
    STUDY_ACTION_SELECTED: 'STUDY_ACTION_SELECTED',
    STUDY_REINFORCEMENT_ANSWERED: 'STUDY_REINFORCEMENT_ANSWERED',
    STUDY_EXITED: 'STUDY_EXITED',

    SESSION_STARTED: 'SESSION_STARTED',
    SESSION_RESUMED: 'SESSION_RESUMED',
    SESSION_PROGRESS: 'SESSION_PROGRESS',
    SESSION_RESULT_ANNOTATED: 'SESSION_RESULT_ANNOTATED',
    SESSION_COMPLETED: 'SESSION_COMPLETED',
    EPISODE_SOURCE_REQUESTED: 'EPISODE_SOURCE_REQUESTED',
    EPISODE_SOURCE_LOADED: 'EPISODE_SOURCE_LOADED',
    EPISODE_SOURCE_FAILED: 'EPISODE_SOURCE_FAILED',
    EPISODE_FALLBACK_ACTIVATED: 'EPISODE_FALLBACK_ACTIVATED',
    EPISODE_READY: 'EPISODE_READY',
    EPISODE_RESTARTED: 'EPISODE_RESTARTED',

    SCORE_CHANGED: 'SCORE_CHANGED',
    STREAK_CHANGED: 'STREAK_CHANGED',
    ERROR_REPORTED: 'ERROR_REPORTED',
    INPUT_COMMAND_DISPATCHED: 'INPUT_COMMAND_DISPATCHED',
    INPUT_COMMAND_REJECTED: 'INPUT_COMMAND_REJECTED',

    CATEGORY_SELECTED: 'CATEGORY_SELECTED',
    CLUE_SELECTED: 'CLUE_SELECTED',
    CLUE_LOADED: 'CLUE_LOADED',
    CLUE_REVEALED: 'CLUE_REVEALED',

    ANSWER_SUBMITTED: 'ANSWER_SUBMITTED',
    ANSWER_CORRECT: 'ANSWER_CORRECT',
    ANSWER_INCORRECT: 'ANSWER_INCORRECT',
    ANSWER_REVEALED: 'ANSWER_REVEALED',

    STREAK_MILESTONE: 'STREAK_MILESTONE',

    QUESTIONS_REQUESTED: 'QUESTIONS_REQUESTED',
    QUESTIONS_LOADED: 'QUESTIONS_LOADED',
    QUESTIONS_FAILED: 'QUESTIONS_FAILED',

    SHARD_REQUESTED: 'SHARD_REQUESTED',
    SHARD_LOADED: 'SHARD_LOADED',
    SHARD_FAILED: 'SHARD_FAILED',

    MEDIA_PREFLIGHT_STARTED: 'MEDIA_PREFLIGHT_STARTED',
    MEDIA_PREFLIGHT_PASSED: 'MEDIA_PREFLIGHT_PASSED',
    MEDIA_PREFLIGHT_REJECTED: 'MEDIA_PREFLIGHT_REJECTED',
    MEDIA_PREFLIGHT_EXHAUSTED: 'MEDIA_PREFLIGHT_EXHAUSTED',
    MEDIA_RUNTIME_FAILED: 'MEDIA_RUNTIME_FAILED',

    HOST_CHANGED: 'HOST_CHANGED',
    HOST_PACK_CHANGED: 'HOST_PACK_CHANGED',
    HOST_PERFORMANCE_DIRECTED: 'HOST_PERFORMANCE_DIRECTED',
    HOST_EXPRESSION_CHANGED: 'HOST_EXPRESSION_CHANGED',
    HOST_QUIP_REQUESTED: 'HOST_QUIP_REQUESTED',
    HOST_QUIP_SELECTED: 'HOST_QUIP_SELECTED',

    AUDIO_REQUESTED: 'AUDIO_REQUESTED',
    AUDIO_READY: 'AUDIO_READY',
    AUDIO_PLAYED: 'AUDIO_PLAYED',
    AUDIO_FAILED: 'AUDIO_FAILED',
    AUDIO_MUTED: 'AUDIO_MUTED',

    VOICE_ENABLED: 'VOICE_ENABLED',
    VOICE_DISABLED: 'VOICE_DISABLED',
    VOICE_LISTENING: 'VOICE_LISTENING',
    VOICE_TRANSCRIPT: 'VOICE_TRANSCRIPT',
    VOICE_COMMAND: 'VOICE_COMMAND',
    VOICE_FAILED: 'VOICE_FAILED',

    TELEMETRY_RECORDED: 'TELEMETRY_RECORDED',
  });

  const NetworkStates = Object.freeze({
    ONLINE: 'online',
    DEGRADED: 'degraded',
    OFFLINE: 'offline',
  });

  const AudioStates = Object.freeze({
    READY: 'ready',
    BUFFERING: 'buffering',
    FAILED: 'failed',
    MUTED: 'muted',
  });

  const ScoreRules = Object.freeze({
    correctMultiplier: 1,
    incorrectScoreMode: 'reset-to-zero',
    streakMilestones: [3, 5, 10],
    allowNegativeScore: false,
  });

  return {
    GameEvents,
    NetworkStates,
    AudioStates,
    ScoreRules,
  };
}));
